mongodb.username=devuser
mongodb.password=dev123
mongodb.host=localhost
mongodb.port=27017
mongodb.database.piano=pianoDev
mongodb.collection.yamahaPiano=yamahaPiano

server.servlet.context-path=/instrument-fetch