# mongo setup
mongodb.username=devuser
mongodb.password=dev123
mongodb.host=localhost
mongodb.port=27017
mongodb.database.piano=pianoDev
mongodb.collection.yamahaPiano=yamahaPiano

server.servlet.context-path=/instrument-fetch

# security
user.oauth.clientId=devAccessClient
user.oauth.clientSecret=devAccess@123
user.oauth.redirectUris=http:://localhost:8080/instrument-fetch

user.oauth.user.username=devuser
user.oauth.password=dev123
user.oauth.accessTokenValidity=300
user.oauth.refreshTokenValidity=240000